### ISSUE TITLE
Allow us to change canvas size

### ISSUE THREAD

**Issue by Ryrynz** [bricelam/ImageResizer#127] opened 2019-02-20 00:01 UTC
I'd like this program to be able to change the canvas size of an image.
If it detects an image size of say 649 x 767 with a single click I could make this 767 x 767.

**Comment by JNavas2** [comment] 2019-02-20 00:02
In other words, you want cropping in addition to resizing?

**Comment by Ryrynz** [comment] 2019-02-20 00:26
Cropping (cutting) may be useful too, essentially it's reverse cropping adding extra colored space (typically white or black) to the image so that when it's uploaded to some sites cropping doesn't occur to the image.

**Comment by JNavas2** [comment] 2019-02-20 00:30
So this is a duplicate of Issue #122?

**Comment by Ryrynz** [comment] 2019-02-20 00:43
Correct. Thanks.

**Comment by Ryrynz** [comment] 2019-02-24 10:14
This is something that requires image editors to usually perform so I'd really like a one click option.
In the settings this could be set as 
Change canvas size to:
Highest vertical or horizontal resolution (thus making a square image) or a user defined size.

**Comment by JNavas2** [comment] 2019-02-24 17:38
@Ryrynz 
It seems to me that you put your finger on it, that this is something more appropriate to image editors than to a simple resizing utility, and I personally don't think that kind of enhancement (feature creep) is warranted. You might want to look into [IrfanView](https://www.irfanview.com/) and [ImageMagick](https://www.imagemagick.org/).

**Comment by Ryrynz** [comment] 2019-02-25 05:49
It's that this is AFAIA the only tool that can/would do this sort of image manipulation simply via context menu. This is still image resizing, just not upscaling the image and is I believe still within the scope of this tool.

**Comment by JNavas2** [comment] 2019-02-25 06:01
@Ryrynz
That's resizing the canvas, not the image, and either cropping the image or filling the canvas, on top of image resizing, which would more than double the settings, and add considerable logic. Then someone will want texture, gradient, and/or bitmap fill on the canvas. Someone else will want frames. etc. etc. That's what happens once feature creep starts. Meanwhile, IrfanView can also be invoked from a context menu, and will do what you want..

**Comment by bricelam** [comment] 2019-03-04 17:59
We have limited cropping abilities. If you select **Fill** and the ratio of the size you specify is different than the image's, the image is scaled down to fill either the width or the height (whichever doesn't leave a gap) and the image is cropped to match the specified size.

Any additional cropping functionality is outside the scope of this utility. Simplicity is what separates Image Resizer from other more advanced solutions.

**Closed by bricelam** 2019-03-04 17:59 UTC
