### ISSUE TITLE
Option for language

### ISSUE THREAD

**Issue by thoral** [bricelam/ImageResizer#83] opened 2018-04-24 14:19 UTC
I'd like to have an option to switch the interface language. I would prefer English instead of German. First, because there is a typo in the German GUI ('past' instead of 'passt'). 

Second, and much more important, I don't like it when a target filenames includes the German grapheme 'ß' when altering the filename after scaling e. g.: 
my_image (Groß).jpg

Instead, I would prefer to use a filename like my_image (medium).jpg as before in version 3.0.0.0.

Edit: I just noticed that I can change the suffixes, so issue no. 2 has been resolved...!

Thank you for this very useful tool!

Thorsten

**Comment by bricelam** [comment] 2018-04-24 16:43
Duplicate of #55

**Closed by bricelam** 2018-04-24 16:43 UTC

**Comment by thoral** [comment] 2018-04-24 17:57
Could you please change the typo in the German GUI? ('past'/'passt')

**Comment by bricelam** [comment] 2018-04-24 18:40
@thoral Sure. You can also review and edit the translation over at https://poeditor.com/join/project/fqkB4t3mez
