### ISSUE TITLE
feature request: remove personal exif metadata while resizing

### ISSUE THREAD

**Issue by ekmor** [bricelam/ImageResizer#24] opened 2016-10-10 15:11 UTC
I usually resize pictures in order to share them. It would be nice if  the resised picture have all personal exif metadata removed.

**Comment by jdunn0** [comment] 2016-10-11 03:26
I'm curious what metadata you would consider personal that needs to be removed as unless you fill the data yourself, the only personal data would be the location where the picture was taken (if the camera/smartphone has a GPS function to figure that out).

**Comment by ekmor** [comment] 2016-10-11 06:49
**All personal information e.g:** 
Description: (Comment/Tags)
Origin: (Author/Date taken /Program name)
Image: (image ID)
Camera: (Camera maker/Camera model)
GPS: (Latitude /Longitude/Altitude)
Etc . . .

**Comment by bricelam** [comment] 2016-10-11 17:39
I looked into doing something similar in #3, but gave up.

I'm not sure this specific feature belongs in this utility, however it could be covered by a more general feature that I've considered in the past: Remove ALL metadata.

Also, categorizing as things as "personal information" is very subjective. Windows has a feature to do this per file, and they leave it entirely up to the user:

![image](https://cloud.githubusercontent.com/assets/1226749/19281392/f0790d9a-8f9e-11e6-8513-80cc108f3b92.png)

**Comment by bricelam** [comment] 2016-10-11 17:43
I'm going to close this issue as wontfix and/or a dupe of #3.

**Closed by bricelam** 2016-10-11 17:43 UTC
Labels: duplicate, enhancement, wontfix

**Comment by YuryKomar** [comment] 2019-07-21 12:39
I will say more - removing of metadata will more decrease the size of outgoing picture. Manage it and awaiting new release...

**Comment by JNavas2** [comment] 2019-07-21 16:09
@YuryKomar 
This issue is closed. Use Issue #3 instead.
