### ISSUE TITLE
small images are huge files

### ISSUE THREAD

**Issue by samgribley** [bricelam/ImageResizer#141] opened 2019-08-04 11:38 UTC
I've recently been using ImageResizer to make thumbnails, but I find that when resizing to a tiny size like 128x128, I get quite large file sizes, in the ~750 kB range.  I assume there is metadata and maybe a thumbnail embedded in that to account for the file size?  If I resize with another program, I get something more like 15 kB.  

Would it be possible to have a "image-only" mode that drops the thumbnail and other extraneous data?

**Comment by bricelam** [comment] 2019-08-05 15:45
Duplicate of #3

**Closed by bricelam** 2019-08-05 15:45 UTC
