### ISSUE TITLE
Use the current folder name as part of the image file name

### ISSUE THREAD

**Issue by devedsmith** [bricelam/ImageResizer#76] opened 2018-04-13 16:47 UTC
Hey Brice, first, thank you for updating the Resizer. LOVE IT.

There are a couple of issues we're having that have caused us to revert to the 2016 installer:

1. Delete confirmation: This has already been mentioned in another post. Resizer is not very practical with the delete confirmation.
2. JPEG quality level does not compress: I've done several tests where I resize an image at various JPEG quality levels. Although the image appears to change quality, the actual file size never changes. PNG interlacing and TIFF compression both appear in the window but do not have any impact on JPEG encoding.

That's all I have for now. Again, great job on it and we love it.

Oh, a suggestion, would be great to be able to use the current folder name as part of the image file name.

mr.smith

**Comment by bricelam** [comment] 2018-04-14 18:50
> Delete confirmation

Duplicate of #75

> JPEG quality level does not compress

Outside of my control--I just leverage the Windows Imaging Component. This is just the behavior of the default JPEG codec.

>  Use the current folder name as part of the image file name

Interesting. I'll re-purpose this issue to just track this. I'll wait and see if other users would find it useful too.

**Comment by bricelam** [comment] 2020-04-03 21:36
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)

**Closed by bricelam** 2020-04-03 21:36 UTC
Labels: enhancement
