### ISSUE TITLE
Feature Request - Add option to remove Metadata data on resized images

### ISSUE THREAD

**Issue by Surfingserenity** [bricelam/ImageResizer#132] opened 2019-04-14 16:47 UTC
Hi Brice, thanks for the awesome little app which I use on an almost daily basis!

Would it be possible to please add an option to strip all the metadata(EXIF/IPTC) from resized files?

Sometimes I don't want that data included with pics that will be posted on public platforms etc, as it is now if I need to strip the metadata out I have to use a different program to resize which nullifies some of the advantage/convenience of ImageResizer.

Either way great program and grateful for your time making it.
Regards

**Comment by JNavas2** [comment] 2019-04-14 16:56
See #24

**Comment by Surfingserenity** [comment] 2019-04-14 16:58
Thanks, I didn't see that.
Well hopefully Brice will perhaps see my new request and consider this feature.

**Comment by bricelam** [comment] 2019-04-17 16:51
Duplicate of #3

**Closed by bricelam** 2019-04-17 16:51 UTC
