### ISSUE TITLE
Delete file on resize

### ISSUE THREAD

**Issue by nchantim** [bricelam/ImageResizer#92] opened 2018-05-02 20:32 UTC
When using the "Resize the original pictures" option, the program now asks to delete the file before overwriting it with the temporary resized file. 
We didn't used to have to be asked to delete on Every. Single. File, the program did that automatically.

**Comment by bricelam** [comment] 2018-05-02 20:34
Duplicate of #75. Will be fixed in version 3.1.1

**Closed by bricelam** 2018-05-02 20:34 UTC
