### ISSUE TITLE
Always convert to target format

### ISSUE THREAD

**Issue by mrdnote** [bricelam/ImageResizer#90] opened 2018-05-01 21:26 UTC
Would be great if there is an option to always convert to jpg. Now images are resized and saved in the source format.

**Comment by bricelam** [comment] 2018-05-02 20:36
Duplicate of #68. Won't fix. See [comment](https://github.com/bricelam/ImageResizer/issues/68#issuecomment-379957996).

**Closed by bricelam** 2018-05-02 20:36 UTC
