### ISSUE TITLE
JPG files named as a JPEG

### ISSUE THREAD

**Issue by alansharkey** [bricelam/ImageResizer#91] opened 2018-05-02 14:49 UTC
Just updated to the latest version. Resized a file which had .jpg as the source extension. The target had .jpeg as the target. Can you leave it as per the source please?

**Comment by bricelam** [comment] 2018-05-02 20:34
Duplicate of #89. Original extension will be preserved in version 3.1.1

**Closed by bricelam** 2018-05-02 20:34 UTC
