### ISSUE TITLE
Can't resize.. Could not find the file c:\p...

### ISSUE THREAD

**Issue by xirbbrix** [bricelam/ImageResizer#96] opened 2018-05-04 07:10 UTC
Hi!
Love this program. Hard to work without it. :)
After update I get this error:
![image](https://user-images.githubusercontent.com/38973147/39616295-f7d64b1e-4f7a-11e8-8006-fcced47ffa19.png)

Not sure if it's a bug or my local system that fails after the upgrade?

**Comment by steveroot** [comment] 2018-05-04 07:48
I read another post that said a restart may be required (related to how windows explorer knows what to run when you use the right-click link), have you tried that already?

**Comment by steveroot** [comment] 2018-05-04 10:34
That's good news.

For future referencing, I just realised this is a duplicate of issue #70

**Closed** 2018-05-04 15:10 UTC
