### ISSUE TITLE
Error while installing and when resizing

### ISSUE THREAD

**Issue by nicksimoneau** [bricelam/ImageResizer#77] opened 2018-04-13 19:25 UTC
At the end of installation got the same issue explorer.exe wasn't restart automaticly (windows 10 64)
 When I try to resize I got error  (French translation to english):

 Unable to resize (P  The file "C:\P" doesnt exist
16628 the file c:\windows\system32\16628 doesnt exist  

![image](https://user-images.githubusercontent.com/10252868/38754218-ece8a410-3f2e-11e8-8f7d-2a77fa71b727.png)

And I LOVE you app 👍

**Comment by nicksimoneau** [comment] 2018-04-13 19:31
Problem fixed !!

Uninstall, Reboot, Reinstall TADAM (windows 95 sound) !

**Comment by bricelam** [comment] 2018-04-14 18:55
Duplicate of #70

Were you asked to restart after installing?

**Closed** 2018-04-14 18:55 UTC

**Comment by nicksimoneau** [comment] 2018-04-14 18:57
No

⁣Envoyé par TypeApp ​

Le 14 avr. 2018 14:56, à 14:56, Brice Lambson <notifications@github.com> a écrit:
