### ISSUE TITLE
Problema with beta

### ISSUE THREAD

**Issue by Filoz** [bricelam/ImageResizer#42] opened 2017-04-28 08:22 UTC
Hi, 
The stable version worked fine; I'm now trying the beta but every time I start click on "resize" button I get the following error:

![cattura](https://cloud.githubusercontent.com/assets/5341996/25520514/7c9138ee-2bfc-11e7-934e-8fce2b9d190e.PNG)

Note: "Impossibile trovare il file" means "Impossible to find the file"

**Comment by Filoz** [comment] 2017-04-28 08:24
I've found the problem:
the path of the file contains a space " " 
removing the space from the folder name makes it work.

**Comment by JNavas2** [comment] 2017-04-28 13:36
Beta works properly here on Win8.1 x64 with spaces in path and file name:
"C:\Users\John\Desktop\New folder\IMG Original.jpg" 
What version of Windows are you using?
Have you tried uninstalling and then reinstalling the Beta?

**Comment by mrkrch** [comment] 2017-05-31 23:00
I have this same problem. I'm running Windows 10 Enterprise 1703 x64.

There are no spaces in the path to the image, it's just on my desktop; and I also tried removing the spaces in the naming scheme setting in the app, but it didn't help.

No combination of settings fixes this problem. Had to uninstall.

**Comment by JNavas2** [comment] 2017-05-31 23:16
Did you try uninstalling, then installing the Beta?

**Comment by mrkrch** [comment] 2017-05-31 23:55
Yes, I did, but that didn't help.

But I just uninstalled everything & rebooted, then installed the beta again, and now it's working.

So apparently you just need to reboot after uninstalling the previous version.

**Comment by JNavas2** [comment] 2017-05-31 23:58
You should ALWAYS reboot after any uninstall because some files can only be removed during boot.

**Comment by bricelam** [comment] 2018-01-28 19:39
Duplicate of #37

**Closed by bricelam** 2018-01-28 19:39 UTC
